# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_auto_20160213_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
