# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0008_following'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='following',
            new_name='follow',
        ),
    ]
