# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0011_auto_20160214_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='from_person',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='to_person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='relationships',
        ),
        migrations.AddField(
            model_name='person',
            name='otherpeople',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
