# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0012_auto_20160214_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='socialnetwork-photo'),
        ),
    ]
