# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0015_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, db_column='image', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.profile'),
        ),
    ]
