# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0016_auto_20160220_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('post', models.ForeignKey(blank=True, db_column='post', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.Item')),
            ],
        ),
    ]
