# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0017_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(blank=True, db_column='post', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='socialnetwork.Item'),
        ),
    ]
