# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0019_comments_mypro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
